### ISSUE TITLE
Inappropriate value for attribute "execution_role_arn": string required.

### ISSUE THREAD

**Issue by MateuszS-Qlos** [Infrastrukturait/terraform-aws-ebs-volume#6]
Receiving a information about the missing value for the execution_role_arn variable. 
 

```
terraform {
    source = "${get_parent_terragrunt_dir()}/../vendor//modules/ebs"
}

dependency "ec2" {
  config_path = "../ec2"
}



include {
  path = find_in_parent_folders()
}


inputs = {
  availability_zone             = "eu-central-1a"
  backup_ebs_iam_role_name      = "dlm-lifecycle-role"
  backup_ebs_period             = 24
  backup_ebs_retention          = 7
  backup_ebs_role_policy_name   = "dlm-lifecycle-policy"
  backup_ebs_start_time         = "03:00"
  enable_backup                 = true
  encrypted                     = false
  final_snapshot                = false
  multi_attach_enabled          = false
  name                          = "rancher2"
  size                          = 50 
  type                          = "gp3"
}`
```

 
 **var.execution_role_arn
  Enter a value:** 
  
 
 
 **Log:**
 

│ Error: Incorrect attribute value type
│ 
│   on main.tf line 79, in resource "aws_iam_role_policy" "dlm_lifecycle_policy":
│   79:   role  = aws_iam_role.dlm_lifecycle_role.*.id
│     ├────────────────
│     │ aws_iam_role.dlm_lifecycle_role is tuple with 1 element
│ 
│ Inappropriate value for attribute "role": string required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 110, in resource "aws_dlm_lifecycle_policy" "backup":
│  110:   execution_role_arn = aws_iam_role.dlm_lifecycle_role.*.arn
│     ├────────────────
│     │ aws_iam_role.dlm_lifecycle_role is tuple with 1 element
│ 
│ Inappropriate value for attribute "execution_role_arn": string require`

**Comment by rafalmasiarek** [comment]
please upgrade your module from vendor to `v0.3.0`
